### ISSUE TITLE
Coming soon badges

### ISSUE THREAD

**Issue by mkucharz** [hacklag/hacklag-website#79]

**Comment by mkucharz** [comment]
<img width="662" alt="hacklag_-_creative_workspace" src="https://cloud.githubusercontent.com/assets/4037961/19219868/1c1e2916-8e1f-11e6-9cd4-08d36e270ed4.png">

**Comment by kamilant** [comment]
![screen shot 2016-10-12 at 11 15 59](https://cloud.githubusercontent.com/assets/22390671/19304523/531339a2-906d-11e6-8f6f-3b5b8039c311.png)
@mkucharz @Idered Is this ok? Adding "comming soon" to h4 tag breaks the layout so I choose to put "comming soon" in the button.

**Comment by Idered** [comment]
@kamilant 

``` css
.badge {
    font-size: 10px;
    display: inline-block;
    padding: 0px 5px;
    background: #e5e5e5;
    border-radius: 3px;
    color: #999;
    font-weight: bold;
    line-height: 21px;
    text-transform: uppercase;
    float: right;
}
```

![](http://i.imgur.com/NKg9E4q.png)

![](http://i.imgur.com/f4KOaWc.png)
